version: '3.8'

volumes:
  db_app:

services:

  db: 
    image: mysql/mysql-server
    networks:
      - demo
    environment:
      - MYSQL_ROOT_PASSWORD="root"
    volumes:
      - ../ops:/docker-entrypoint-initdb.d
      - db_app:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    networks:
      - demo
    container_name: api
    # ports:
    #   - "4000:4000"
    env_file:
      - ./.env
    volumes:
      - ./:/app
    command: sh -c 'npm install --prefix /app && npm run start'
    restart: on-failure
    depends_on:
      - db

  proxy: 
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ../ops/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - demo
    depends_on:
      - app

networks:
  demo: